### PR TITLE
Center modal dialog messages and fix save message

### PR DESCRIPTION
**Pull request by TONYFECTEAU**
- The save message needs to have two paragraphs.
- The modal message requires a vertical centering.

Story [AB#42860](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42860)

### CODE REVIEW

**Comment by InnaBoitsun** [comment]
@TONYFECTEAU to link Stories to GITHUB repo need to use reference like this AB#NUMBER
AB#42860

**Comment by TONYFECTEAU** [comment]
> @TONYFECTEAU to link Stories to GITHUB repo need to use reference like this AB#NUMBER
> [AB#42860](https://dev.azure.com/orckestra001/da965986-c85b-43be-9915-219568b000e5/_workitems/edit/42860)

Ok, I was unaware.  Thanks.

**Comment by InnaBoitsun** [comment]
I tested and see next. Did you have screen how it looks on your side?:
image

**Comment by joclefrancois** [comment]
Can you uncommit unmodified files that were only reformatted pleased ? And also undo unnecessary reformatting from the file you modified ? Thanks

**Comment by TONYFECTEAU** [comment]
> I tested and see next. Do you have screen how it looks on your side?:
> image

Hm!  I had this... 
image

I think I know what is wrong... fixes coming up.

**Comment by TONYFECTEAU** [comment]
> I tested and see next. Do you have screen how it looks on your side?:
> image

Ok, fixed.  It was the way I was testing the component.  Thanks for catching this.

**Review by khanvong-ork — APPROVED** [review]

**Review by InnaBoitsun — APPROVED** [review]

**Pull request merged**
